package com.fvgprinc.app.jpatestpkcomp.ui;

import com.fvgprinc.app.jpatestpkcomp.be.Cliente;
import com.fvgprinc.app.jpatestpkcomp.be.Cuenta;
import com.fvgprinc.app.jpatestpkcomp.be.CuentaId;
import com.fvgprinc.app.jpatestpkcomp.bl.ClienteBl;
import com.fvgprinc.app.jpatestpkcomp.bl.CuentaBl;
import com.fvgprinc.tools.string.MyCommonString;
import com.fvgprinc.tools.utilities.MyDouble;
import com.fvgprinc.tools.utilities.MySwingUtil;
import static com.fvgprinc.tools.utilities.MySwingUtil.FrmStates;

/**
 *
 * @author garfi
 */
public class JfrmDlgCuentaMnt extends javax.swing.JDialog {

    private ClienteBl clienteBl;
    private CuentaBl cuentaBl;
    private Cuenta cuenta;
    private FrmStates frmStatus;

    /**
     * Creates new form JfrmDlgMnt
     *
     * @param parent
     * @param modal
     */
    public JfrmDlgCuentaMnt(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public JfrmDlgCuentaMnt(java.awt.Frame parent, boolean modal, ClienteBl clienteBl, CuentaBl cuentaBl,
            Cuenta cuenta, FrmStates frmStatus) {
        super(parent, modal);
        initComponents();
        this.clienteBl = clienteBl;
        this.cuentaBl = cuentaBl;
        this.frmStatus = frmStatus;
        switch (this.frmStatus) {
            case FRMINSERT -> {
                jTxtFldIdClienteN.setText(MyCommonString.EMPTYSTR);
                jTxtFldIdCuentaN.setText(MyCommonString.EMPTYSTR);
                jTxtFldNomCuenta.setText(MyCommonString.EMPTYSTR);
            }
            case FRMUPDATE -> {
                if (cuenta != null) {
                    this.cuenta = cuenta;
                    jTxtFldIdClienteN.setEnabled(false);
                    jTxtFldIdCuentaN.setEnabled(false);
                    jTxtFldIdClienteN.setText(String.valueOf( cuenta.getId().getIdClienteN()));
                    jTxtFldIdCuentaN.setText( String.valueOf(cuenta.getId().getIdCuentaN()));
                    jTxtFldNomCuenta.setText(cuenta.getNomCuenta());
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtFldIdClienteN = new javax.swing.JTextField();
        jTxtFldNomCuenta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jBtnOk = new javax.swing.JButton();
        jBtnCancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTxtFldIdCuentaN = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Cliente:");

        jTxtFldIdClienteN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTxtFldNomCuenta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nombre:");

        jBtnOk.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBtnOk.setText("Ok");
        jBtnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOkActionPerformed(evt);
            }
        });

        jBtnCancel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBtnCancel.setText("Cancel");
        jBtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Cuenta:");

        jTxtFldIdCuentaN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTxtFldIdClienteN, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(27, 27, 27)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtFldNomCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtFldIdCuentaN, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jBtnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jBtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtFldIdClienteN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtFldIdCuentaN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtFldNomCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnOk)
                    .addComponent(jBtnCancel))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtnCancelActionPerformed
    private CuentaId validarCuentaId(String idClienteStr, String idCuentaStr) {

        CuentaId cuentaId = null;
        int idClienteN = 0;
        int idCuentaN = 0;
        boolean clienteValido;
        boolean cuentaValida = false;
        // validar cliente
        clienteValido = MyDouble.isNumeric(idClienteStr);
        // validar cuenta
        if (idCuentaStr.length() > 0) {
            if (MyDouble.isNumeric(idCuentaStr)) {
                idCuentaN = Integer.parseInt(idCuentaStr);
                cuentaValida = true;
            }
        } else {
            idCuentaN = 0;
            cuentaValida = true;
        }

        if (clienteValido && cuentaValida) {
            idClienteN = Integer.parseInt(idClienteStr);
            cuentaId = new CuentaId(idClienteN, idCuentaN);
        }
        return cuentaId;
    }

    private void jBtnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOkActionPerformed
        switch (this.frmStatus) {
            case FRMINSERT -> {
                CuentaId cuentaId = validarCuentaId(jTxtFldIdClienteN.getText(), jTxtFldIdCuentaN.getText());
                if (cuentaId != null) {
                    int idClienteN = Integer.parseInt(jTxtFldIdClienteN.getText());
                    Cliente cliente = clienteBl.buscarPorId(idClienteN);
                    cuenta = new Cuenta(cuentaId, jTxtFldNomCuenta.getText(), cliente);
                    // Guarda en la BD
                    cuentaBl.crear(cuenta);
                    MySwingUtil.mostrarMensaje("Cuenta ingresada correctamente", MySwingUtil.TD_INFO,
                            "Ingreso de Cuentas");
                } else {
                    MySwingUtil.mostrarMensaje("Numero de cuenta invalida, revisar", MySwingUtil.TD_ERROR,
                            "Ingreso de Cuentas");
                }
            } 

            case FRMUPDATE -> {
                   cuenta.setNomCuenta(jTxtFldNomCuenta.getText() );
                   cuentaBl.modifcar(cuenta);
                   MySwingUtil.mostrarMensaje("Cuenta modificada correctamente", MySwingUtil.TD_INFO, 
                                                                  "Modificación de Cuentas");
            }
        }
        this.dispose();
    }//GEN-LAST:event_jBtnOkActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancel;
    private javax.swing.JButton jBtnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtFldIdClienteN;
    private javax.swing.JTextField jTxtFldIdCuentaN;
    private javax.swing.JTextField jTxtFldNomCuenta;
    // End of variables declaration//GEN-END:variables

}
