package com.fvgprinc.app.jpatestpkcomp.ui;
import com.fvgprinc.app.jpatestpkcomp.be.Cliente;
import com.fvgprinc.app.jpatestpkcomp.be.Cuenta;
import com.fvgprinc.app.jpatestpkcomp.bl.ClienteBl;
import com.fvgprinc.tools.string.MyCommonString;
import com.fvgprinc.tools.utilities.MySwingUtil;
import static com.fvgprinc.tools.utilities.MySwingUtil.FrmStates;
import java.util.ArrayList;

/**
 *
 * @author garfi
 */
public class JfrmDlgClienteMnt extends javax.swing.JDialog {

    
    private ClienteBl clienteBl;
    private Cliente cliente;
    private FrmStates frmStatus;

    /**
     * Creates new form JfrmDlgMnt
     * @param parent
     * @param modal
     */
    public JfrmDlgClienteMnt(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    
    public JfrmDlgClienteMnt(java.awt.Frame parent, boolean modal, ClienteBl clienteBl, 
                                              Cliente cliente,  FrmStates frmStatus) {
        super(parent, modal);
        initComponents();
        this.clienteBl = clienteBl;
        this.frmStatus = frmStatus;
        switch (this.frmStatus) {
            case FRMINSERT -> {
                jTxtFldCodClienteN.setText(MyCommonString.EMPTYSTR);
                jTxtFldNomCliente.setText(MyCommonString.EMPTYSTR);
            }
            case FRMUPDATE -> {
                if (cliente != null) {
                    this.cliente = cliente;
                    jTxtFldCodClienteN.setEnabled(false);
                    jTxtFldCodClienteN.setText( Integer.toString(cliente.getIdClienteN()));
                    jTxtFldNomCliente.setText(cliente.getNomCliente());
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtFldCodClienteN = new javax.swing.JTextField();
        jTxtFldNomCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jBtnOk = new javax.swing.JButton();
        jBtnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Cliente:");

        jTxtFldCodClienteN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTxtFldNomCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nombre:");

        jBtnOk.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBtnOk.setText("Ok");
        jBtnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOkActionPerformed(evt);
            }
        });

        jBtnCancel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBtnCancel.setText("Cancel");
        jBtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTxtFldCodClienteN, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jTxtFldNomCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jBtnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtFldCodClienteN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtFldNomCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnOk)
                    .addComponent(jBtnCancel))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtnCancelActionPerformed

    private void jBtnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOkActionPerformed
        switch (this.frmStatus) {
            case FRMINSERT -> {
                ArrayList<Cuenta> lstCuentas = new ArrayList<>();
                int idClienteN = 0;
                if (jTxtFldCodClienteN.getText().length() > 0) {
                    idClienteN = Integer.parseInt(jTxtFldCodClienteN.getText());
                }
                cliente = new Cliente(idClienteN, jTxtFldNomCliente.getText(), lstCuentas);
                // Guarda en la BD
                clienteBl.crear(cliente);
                MySwingUtil.mostrarMensaje("Cliente ingresada correctamente", MySwingUtil.TD_INFO,
                        "Ingreso de Clientes");
            }
            case FRMUPDATE ->{
                cliente.setIdClienteN(Integer.parseInt(jTxtFldCodClienteN.getText()));
                cliente.setNomCliente(jTxtFldNomCliente.getText());
                clienteBl.modificar(cliente);
                MySwingUtil.mostrarMensaje("Cliente modificada correctamente", MySwingUtil.TD_INFO, 
                                                                "Modificar Clientes");
            }
        }
        this.dispose();
    }//GEN-LAST:event_jBtnOkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancel;
    private javax.swing.JButton jBtnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtFldCodClienteN;
    private javax.swing.JTextField jTxtFldNomCliente;
    // End of variables declaration//GEN-END:variables
}
